from mongoengine import DateField, Document, FloatField, StringField


class Balancesheet(Document):
    """
    资产负债表
    """

    ticker = StringField(required=True)
    freq = StringField(required=True)
    end_date = DateField(required=True)
    TreasurySharesNumber = FloatField()
    PreferredSharesNumber = FloatField()
    OrdinarySharesNumber = FloatField()
    ShareIssued = FloatField()
    NetDebt = FloatField()
    TotalDebt = FloatField()
    TangibleBookValue = FloatField()
    InvestedCapital = FloatField()
    WorkingCapital = FloatField()
    NetTangibleAssets = FloatField()
    CapitalLeaseObligations = FloatField()
    CommonStockEquity = FloatField()
    PreferredStockEquity = FloatField()
    TotalCapitalization = FloatField()
    TotalEquityGrossMinorityInterest = FloatField()
    MinorityInterest = FloatField()
    StockholdersEquity = FloatField()
    OtherEquityInterest = FloatField()
    GainsLossesNotAffectingRetainedEarnings = FloatField()
    OtherEquityAdjustments = FloatField()
    FixedAssetsRevaluationReserve = FloatField()
    ForeignCurrencyTranslationAdjustments = FloatField()
    MinimumPensionLiabilities = FloatField()
    UnrealizedGainLoss = FloatField()
    TreasuryStock = FloatField()
    RetainedEarnings = FloatField()
    AdditionalPaidInCapital = FloatField()
    CapitalStock = FloatField()
    OtherCapitalStock = FloatField()
    CommonStock = FloatField()
    PreferredStock = FloatField()
    TotalPartnershipCapital = FloatField()
    GeneralPartnershipCapital = FloatField()
    LimitedPartnershipCapital = FloatField()
    TotalLiabilitiesNetMinorityInterest = FloatField()
    TotalNonCurrentLiabilitiesNetMinorityInterest = FloatField()
    OtherNonCurrentLiabilities = FloatField()
    LiabilitiesHeldforSaleNonCurrent = FloatField()
    RestrictedCommonStock = FloatField()
    PreferredSecuritiesOutsideStockEquity = FloatField()
    DerivativeProductLiabilities = FloatField()
    EmployeeBenefits = FloatField()
    NonCurrentPensionAndOtherPostretirementBenefitPlans = FloatField()
    NonCurrentAccruedExpenses = FloatField()
    DuetoRelatedPartiesNonCurrent = FloatField()
    TradeandOtherPayablesNonCurrent = FloatField()
    NonCurrentDeferredLiabilities = FloatField()
    NonCurrentDeferredRevenue = FloatField()
    NonCurrentDeferredTaxesLiabilities = FloatField()
    LongTermDebtAndCapitalLeaseObligation = FloatField()
    LongTermCapitalLeaseObligation = FloatField()
    LongTermDebt = FloatField()
    LongTermProvisions = FloatField()
    CurrentLiabilities = FloatField()
    OtherCurrentLiabilities = FloatField()
    CurrentDeferredLiabilities = FloatField()
    CurrentDeferredRevenue = FloatField()
    CurrentDeferredTaxesLiabilities = FloatField()
    CurrentDebtAndCapitalLeaseObligation = FloatField()
    CurrentCapitalLeaseObligation = FloatField()
    CurrentDebt = FloatField()
    OtherCurrentBorrowings = FloatField()
    LineOfCredit = FloatField()
    CommercialPaper = FloatField()
    CurrentNotesPayable = FloatField()
    PensionandOtherPostRetirementBenefitPlansCurrent = FloatField()
    CurrentProvisions = FloatField()
    PayablesAndAccruedExpenses = FloatField()
    CurrentAccruedExpenses = FloatField()
    InterestPayable = FloatField()
    Payables = FloatField()
    OtherPayable = FloatField()
    DuetoRelatedPartiesCurrent = FloatField()
    DividendsPayable = FloatField()
    TotalTaxPayable = FloatField()
    IncomeTaxPayable = FloatField()
    AccountsPayable = FloatField()
    TotalAssets = FloatField()
    TotalNonCurrentAssets = FloatField()
    OtherNonCurrentAssets = FloatField()
    DefinedPensionBenefit = FloatField()
    NonCurrentPrepaidAssets = FloatField()
    NonCurrentDeferredAssets = FloatField()
    NonCurrentDeferredTaxesAssets = FloatField()
    DuefromRelatedPartiesNonCurrent = FloatField()
    NonCurrentNoteReceivables = FloatField()
    NonCurrentAccountsReceivable = FloatField()
    FinancialAssets = FloatField()
    InvestmentsAndAdvances = FloatField()
    OtherInvestments = FloatField()
    InvestmentinFinancialAssets = FloatField()
    HeldToMaturitySecurities = FloatField()
    AvailableForSaleSecurities = FloatField()
    FinancialAssetsDesignatedasFairValueThroughProfitorLossTotal = FloatField()
    TradingSecurities = FloatField()
    LongTermEquityInvestment = FloatField()
    InvestmentsinJointVenturesatCost = FloatField()
    InvestmentsInOtherVenturesUnderEquityMethod = FloatField()
    InvestmentsinAssociatesatCost = FloatField()
    InvestmentsinSubsidiariesatCost = FloatField()
    InvestmentProperties = FloatField()
    GoodwillAndOtherIntangibleAssets = FloatField()
    OtherIntangibleAssets = FloatField()
    Goodwill = FloatField()
    NetPPE = FloatField()
    AccumulatedDepreciation = FloatField()
    GrossPPE = FloatField()
    Leases = FloatField()
    ConstructionInProgress = FloatField()
    OtherProperties = FloatField()
    MachineryFurnitureEquipment = FloatField()
    BuildingsAndImprovements = FloatField()
    LandAndImprovements = FloatField()
    Properties = FloatField()
    CurrentAssets = FloatField()
    OtherCurrentAssets = FloatField()
    HedgingAssetsCurrent = FloatField()
    AssetsHeldForSaleCurrent = FloatField()
    CurrentDeferredAssets = FloatField()
    CurrentDeferredTaxesAssets = FloatField()
    RestrictedCash = FloatField()
    PrepaidAssets = FloatField()
    Inventory = FloatField()
    InventoriesAdjustmentsAllowances = FloatField()
    OtherInventories = FloatField()
    FinishedGoods = FloatField()
    WorkInProcess = FloatField()
    RawMaterials = FloatField()
    Receivables = FloatField()
    ReceivablesAdjustmentsAllowances = FloatField()
    OtherReceivables = FloatField()
    DuefromRelatedPartiesCurrent = FloatField()
    TaxesReceivable = FloatField()
    AccruedInterestReceivable = FloatField()
    NotesReceivable = FloatField()
    LoansReceivable = FloatField()
    AccountsReceivable = FloatField()
    AllowanceForDoubtfulAccountsReceivable = FloatField()
    GrossAccountsReceivable = FloatField()
    CashCashEquivalentsAndShortTermInvestments = FloatField()
    OtherShortTermInvestments = FloatField()
    CashAndCashEquivalents = FloatField()
    CashEquivalents = FloatField()
    CashFinancial = FloatField()

    meta = {
        'ordering': ['-end_date'],
        'index_background': True,
        'auto_create_index': True,
        'auto_create_index_on_save': False,
        'indexes': [
            {'fields': ['end_date', 'ticker', 'freq'],
             'unique': True}
        ]

    }


class CashflowTable(Document):
    """
    现金流量表
    """

    ticker = StringField(required=True)
    freq = StringField(required=True)
    end_date = DateField(required=True)
    ForeignSales = FloatField()
    DomesticSales = FloatField()
    AdjustedGeographySegmentData = FloatField()
    FreeCashFlow = FloatField()
    RepurchaseOfCapitalStock = FloatField()
    RepaymentOfDebt = FloatField()
    IssuanceOfDebt = FloatField()
    IssuanceOfCapitalStock = FloatField()
    CapitalExpenditure = FloatField()
    InterestPaidSupplementalData = FloatField()
    IncomeTaxPaidSupplementalData = FloatField()
    EndCashPosition = FloatField()
    OtherCashAdjustmentOutsideChangeinCash = FloatField()
    BeginningCashPosition = FloatField()
    EffectOfExchangeRateChanges = FloatField()
    ChangesInCash = FloatField()
    OtherCashAdjustmentInsideChangeinCash = FloatField()
    CashFlowFromDiscontinuedOperation = FloatField()
    FinancingCashFlow = FloatField()
    CashFromDiscontinuedFinancingActivities = FloatField()
    CashFlowFromContinuingFinancingActivities = FloatField()
    NetOtherFinancingCharges = FloatField()
    InterestPaidCFF = FloatField()
    ProceedsFromStockOptionExercised = FloatField()
    CashDividendsPaid = FloatField()
    PreferredStockDividendPaid = FloatField()
    CommonStockDividendPaid = FloatField()
    NetPreferredStockIssuance = FloatField()
    PreferredStockPayments = FloatField()
    PreferredStockIssuance = FloatField()
    NetCommonStockIssuance = FloatField()
    CommonStockPayments = FloatField()
    CommonStockIssuance = FloatField()
    NetIssuancePaymentsOfDebt = FloatField()
    NetShortTermDebtIssuance = FloatField()
    ShortTermDebtPayments = FloatField()
    ShortTermDebtIssuance = FloatField()
    NetLongTermDebtIssuance = FloatField()
    LongTermDebtPayments = FloatField()
    LongTermDebtIssuance = FloatField()
    InvestingCashFlow = FloatField()
    CashFromDiscontinuedInvestingActivities = FloatField()
    CashFlowFromContinuingInvestingActivities = FloatField()
    NetOtherInvestingChanges = FloatField()
    InterestReceivedCFI = FloatField()
    DividendsReceivedCFI = FloatField()
    NetInvestmentPurchaseAndSale = FloatField()
    SaleOfInvestment = FloatField()
    PurchaseOfInvestment = FloatField()
    NetInvestmentPropertiesPurchaseAndSale = FloatField()
    SaleOfInvestmentProperties = FloatField()
    PurchaseOfInvestmentProperties = FloatField()
    NetBusinessPurchaseAndSale = FloatField()
    SaleOfBusiness = FloatField()
    PurchaseOfBusiness = FloatField()
    NetIntangiblesPurchaseAndSale = FloatField()
    SaleOfIntangibles = FloatField()
    PurchaseOfIntangibles = FloatField()
    NetPPEPurchaseAndSale = FloatField()
    SaleOfPPE = FloatField()
    PurchaseOfPPE = FloatField()
    CapitalExpenditureReported = FloatField()
    OperatingCashFlow = FloatField()
    CashFromDiscontinuedOperatingActivities = FloatField()
    CashFlowFromContinuingOperatingActivities = FloatField()
    TaxesRefundPaid = FloatField()
    InterestReceivedCFO = FloatField()
    InterestPaidCFO = FloatField()
    DividendReceivedCFO = FloatField()
    DividendPaidCFO = FloatField()
    ChangeInWorkingCapital = FloatField()
    ChangeInOtherWorkingCapital = FloatField()
    ChangeInOtherCurrentLiabilities = FloatField()
    ChangeInOtherCurrentAssets = FloatField()
    ChangeInPayablesAndAccruedExpense = FloatField()
    ChangeInAccruedExpense = FloatField()
    ChangeInInterestPayable = FloatField()
    ChangeInPayable = FloatField()
    ChangeInDividendPayable = FloatField()
    ChangeInAccountPayable = FloatField()
    ChangeInTaxPayable = FloatField()
    ChangeInIncomeTaxPayable = FloatField()
    ChangeInPrepaidAssets = FloatField()
    ChangeInInventory = FloatField()
    ChangeInReceivables = FloatField()
    ChangesInAccountReceivables = FloatField()
    OtherNonCashItems = FloatField()
    ExcessTaxBenefitFromStockBasedCompensation = FloatField()
    StockBasedCompensation = FloatField()
    UnrealizedGainLossOnInvestmentSecurities = FloatField()
    ProvisionandWriteOffofAssets = FloatField()
    AssetImpairmentCharge = FloatField()
    AmortizationOfSecurities = FloatField()
    DeferredTax = FloatField()
    DeferredIncomeTax = FloatField()
    DepreciationAmortizationDepletion = FloatField()
    Depletion = FloatField()
    DepreciationAndAmortization = FloatField()
    AmortizationCashFlow = FloatField()
    AmortizationOfIntangibles = FloatField()
    Depreciation = FloatField()
    OperatingGainsLosses = FloatField()
    PensionAndEmployeeBenefitExpense = FloatField()
    EarningsLossesFromEquityInvestments = FloatField()
    GainLossOnInvestmentSecurities = FloatField()
    NetForeignCurrencyExchangeGainLoss = FloatField()
    GainLossOnSaleOfPPE = FloatField()
    GainLossOnSaleOfBusiness = FloatField()
    NetIncomeFromContinuingOperations = FloatField()
    CashFlowsfromusedinOperatingActivitiesDirect = FloatField()
    TaxesRefundPaidDirect = FloatField()
    InterestReceivedDirect = FloatField()
    InterestPaidDirect = FloatField()
    DividendsReceivedDirect = FloatField()
    DividendsPaidDirect = FloatField()
    ClassesofCashPayments = FloatField()
    OtherCashPaymentsfromOperatingActivities = FloatField()
    PaymentsonBehalfofEmployees = FloatField()
    PaymentstoSuppliersforGoodsandServices = FloatField()
    ClassesofCashReceiptsfromOperatingActivities = FloatField()
    OtherCashReceiptsfromOperatingActivities = FloatField()
    ReceiptsfromGovernmentGrants = FloatField()
    ReceiptsfromCustomers = FloatField()

    meta = {
        'ordering': ['-end_date'],
        'index_background': True,
        'auto_create_index': True,
        'auto_create_index_on_save': False,
        'indexes': [
            {'fields': ['end_date', 'ticker', 'freq'],
             'unique': True}
        ]

    }


class Financials(Document):
    """
    收入表

    """

    ticker = StringField(required=True)
    freq = StringField(required=True)
    end_date = DateField(required=True)
    TaxEffectOfUnusualItems = FloatField()
    TaxRateForCalcs = FloatField()
    NormalizedEBITDA = FloatField()
    NormalizedDilutedEPS = FloatField()
    NormalizedBasicEPS = FloatField()
    TotalUnusualItems = FloatField()
    TotalUnusualItemsExcludingGoodwill = FloatField()
    NetIncomeFromContinuingOperationNetMinorityInterest = FloatField()
    ReconciledDepreciation = FloatField()
    ReconciledCostOfRevenue = FloatField()
    EBITDA = FloatField()
    EBIT = FloatField()
    NetInterestIncome = FloatField()
    InterestExpense = FloatField()
    InterestIncome = FloatField()
    ContinuingAndDiscontinuedDilutedEPS = FloatField()
    ContinuingAndDiscontinuedBasicEPS = FloatField()
    NormalizedIncome = FloatField()
    NetIncomeFromContinuingAndDiscontinuedOperation = FloatField()
    TotalExpenses = FloatField()
    RentExpenseSupplemental = FloatField()
    ReportedNormalizedDilutedEPS = FloatField()
    ReportedNormalizedBasicEPS = FloatField()
    TotalOperatingIncomeAsReported = FloatField()
    DividendPerShare = FloatField()
    DilutedAverageShares = FloatField()
    BasicAverageShares = FloatField()
    DilutedEPS = FloatField()
    DilutedEPSOtherGainsLosses = FloatField()
    TaxLossCarryforwardDilutedEPS = FloatField()
    DilutedAccountingChange = FloatField()
    DilutedExtraordinary = FloatField()
    DilutedDiscontinuousOperations = FloatField()
    DilutedContinuousOperations = FloatField()
    BasicEPS = FloatField()
    BasicEPSOtherGainsLosses = FloatField()
    TaxLossCarryforwardBasicEPS = FloatField()
    BasicAccountingChange = FloatField()
    BasicExtraordinary = FloatField()
    BasicDiscontinuousOperations = FloatField()
    BasicContinuousOperations = FloatField()
    DilutedNIAvailtoComStockholders = FloatField()
    AverageDilutionEarnings = FloatField()
    NetIncomeCommonStockholders = FloatField()
    OtherunderPreferredStockDividend = FloatField()
    PreferredStockDividends = FloatField()
    NetIncome = FloatField()
    MinorityInterests = FloatField()
    NetIncomeIncludingNoncontrollingInterests = FloatField()
    NetIncomeFromTaxLossCarryforward = FloatField()
    NetIncomeExtraordinary = FloatField()
    NetIncomeDiscontinuousOperations = FloatField()
    NetIncomeContinuousOperations = FloatField()
    EarningsFromEquityInterestNetOfTax = FloatField()
    TaxProvision = FloatField()
    PretaxIncome = FloatField()
    OtherIncomeExpense = FloatField()
    OtherNonOperatingIncomeExpenses = FloatField()
    SpecialIncomeCharges = FloatField()
    GainOnSaleOfPPE = FloatField()
    GainOnSaleOfBusiness = FloatField()
    OtherSpecialCharges = FloatField()
    WriteOff = FloatField()
    ImpairmentOfCapitalAssets = FloatField()
    RestructuringAndMergernAcquisition = FloatField()
    SecuritiesAmortization = FloatField()
    EarningsFromEquityInterest = FloatField()
    GainOnSaleOfSecurity = FloatField()
    NetNonOperatingInterestIncomeExpense = FloatField()
    TotalOtherFinanceCost = FloatField()
    InterestExpenseNonOperating = FloatField()
    InterestIncomeNonOperating = FloatField()
    OperatingIncome = FloatField()
    OperatingExpense = FloatField()
    OtherOperatingExpenses = FloatField()
    OtherTaxes = FloatField()
    ProvisionForDoubtfulAccounts = FloatField()
    DepreciationAmortizationDepletionIncomeStatement = FloatField()
    DepletionIncomeStatement = FloatField()
    DepreciationAndAmortizationInIncomeStatement = FloatField()
    Amortization = FloatField()
    AmortizationOfIntangiblesIncomeStatement = FloatField()
    DepreciationIncomeStatement = FloatField()
    ResearchAndDevelopment = FloatField()
    SellingGeneralAndAdministration = FloatField()
    SellingAndMarketingExpense = FloatField()
    GeneralAndAdministrativeExpense = FloatField()
    OtherGandA = FloatField()
    InsuranceAndClaims = FloatField()
    RentAndLandingFees = FloatField()
    SalariesAndWages = FloatField()
    GrossProfit = FloatField()
    CostOfRevenue = FloatField()
    TotalRevenue = FloatField()
    ExciseTaxes = FloatField()
    OperatingRevenue = FloatField()

    meta = {
        'ordering': ['-end_date'],
        'index_background': True,
        'auto_create_index': True,
        'auto_create_index_on_save': False,
        'indexes': [
            {'fields': ['end_date', 'ticker', 'freq'],
             'unique': True}
        ]

    }
