name: Deploy Miner

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches: [ main ]

jobs:
  run-script:
    runs-on: self-hosted  # This is the key for self-hosted runner
    env:
        # Add your environment variables here
        MINER_ENV: ${{ env.MINER_ENV }}
    
    steps:
    - name: Access the environment variable
      run: |
        echo "The miner environment is set to: ${{ env.MINER_ENV }}"
        echo $MINER_ENV

    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Make script executable
      run: chmod +x Deploy/deploy.sh
      
    - name: Run the script
      run: ./Deploy/deploy.sh
      
        
    - name: Cleanup workspace
      if: always()  # Run cleanup even if previous steps fail
      run: |
        echo "Cleaning up workspace..."
        cd ${{ github.workspace }}
        cd ..
        rm -rf ${{ github.workspace }}/*
        echo "Workspace cleanup completed"
        pwd
        ls -AGl
