name: Build and Deploy StkGuru

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
        working-directory: ./StkGuru

      - name: Install dependencies
        run: npm ci
        working-directory: ./StkGuru

      - name: Build
        run: npm run build:ghpages --if-present
        working-directory: ./StkGuru

      - name: Prepare deploy directory
        run: |
          rm -rf deploy-dist
          mkdir deploy-dist
          cp -r StkGuru/dist/* deploy-dist/

      - name: Clone target repo
        run: |
          git clone --branch main --single-branch https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/stkguru/stkguru.github.io.git target-repo

      - name: Sync build output to target repo
        run: |
          rsync -av --delete deploy-dist/ target-repo/

      - name: Commit and push changes
        run: |
          cd target-repo
          git config user.name "Stk.Guru[bot]"
          git config user.email "205558759+stkguru@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Deploy StkGuru build from source repo: ${{ github.sha }}"
            git pull --rebase
            git push origin gh-pages
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} 
